# -*- coding: utf-8 -*-
"""Streamlit News Alert App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TSVVtE6n0AbtaonjUp0-7AeqT5-OpjZ
"""

import streamlit as st
import pandas as pd
from newspaper import Article, Config, build
import nltk
import ssl

# --- Cấu hình và Thiết lập ban đầu ---

# Cấu hình để bỏ qua xác thực SSL (hữu ích khi một số trang web có chứng chỉ cũ)
# Điều này giúp tránh lỗi khi tải dữ liệu từ một số trang tin
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

# Tải tài nguyên cần thiết cho thư viện newspaper
# Chỉ cần chạy một lần
try:
    nltk.data.find('tokenizers/punkt')
except nltk.downloader.DownloadError:
    nltk.download('punkt')

# Cấu hình cho newspaper3k để tăng tốc và tránh lỗi
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
config = Config()
config.browser_user_agent = user_agent
config.request_timeout = 10 # Thời gian chờ tối đa cho mỗi yêu cầu là 10 giây

# --- Hàm xử lý chính ---

@st.cache_data(ttl=3600) # Lưu kết quả trong 1 giờ (3600 giây) để không phải quét lại liên tục
def load_data(file_path):
    """Hàm để tải dữ liệu từ file CSV và xử lý cơ bản."""
    try:
        # Bỏ qua 2 dòng đầu tiên không cần thiết trong file CSV của bạn
        df = pd.read_csv(file_path, skiprows=2)
        # Đổi tên cột để dễ sử dụng
        df.columns = ['STT', 'Website', 'Keywords']
        # Loại bỏ các dòng không có thông tin Website hoặc Keywords
        df.dropna(subset=['Website', 'Keywords'], inplace=True)
        return df
    except FileNotFoundError:
        st.error(f"Lỗi: Không tìm thấy file '{file_path}'. Vui lòng đảm bảo file này tồn tại trong kho GitHub của bạn.")
        return None

def clean_keywords(keywords_str):
    """Hàm để làm sạch và tách các từ khóa."""
    # Tách chuỗi bằng dấu / hoặc xuống dòng, loại bỏ ký tự '-' và khoảng trắng thừa
    keywords = [kw.strip().lstrip('-').strip() for kw in keywords_str.replace('/', '\n').split('\n')]
    # Loại bỏ các chuỗi rỗng
    return [kw for kw in keywords if kw]

@st.cache_data(ttl=3600)
def find_news_on_site(site_url, keywords):
    """
    Hàm quét một trang web cụ thể để tìm các bài báo chứa từ khóa.
    _site_url: URL của trang web cần quét.
    keywords: Danh sách các từ khóa cần tìm.
    """
    found_articles = []
    try:
        # Sử dụng newspaper để xây dựng một nguồn tin tức từ URL
        st.write(f"Đang quét trang: {site_url}...")
        paper = build(site_url, config=config, memoize_articles=False)

        st.write(f"Tìm thấy {len(paper.articles)} bài viết trên trang chủ. Bắt đầu phân tích...")

        # Giới hạn số lượng bài viết cần phân tích để tăng tốc độ
        articles_to_check = paper.articles[:20]

        for article in articles_to_check:
            try:
                article.download()
                article.parse()

                # Kiểm tra từ khóa trong tiêu đề và nội dung bài viết
                # Chuyển tất cả về chữ thường để tìm kiếm không phân biệt hoa/thường
                article_text = (article.title + ' ' + article.text).lower()

                for keyword in keywords:
                    if keyword.lower() in article_text:
                        # Nếu tìm thấy, lưu lại thông tin và thoát khỏi vòng lặp từ khóa
                        found_articles.append({
                            'title': article.title,
                            'url': article.url,
                            'keyword': keyword
                        })
                        break # Chuyển sang bài báo tiếp theo khi đã tìm thấy một từ khóa
            except Exception as e:
                # Bỏ qua nếu có lỗi khi tải một bài báo cụ thể
                # st.warning(f"Không thể tải bài viết {article.url}. Lỗi: {e}")
                continue
    except Exception as e:
        st.error(f"Không thể truy cập hoặc phân tích trang {site_url}. Lỗi: {e}")

    return found_articles

# --- Giao diện người dùng Streamlit ---

st.set_page_config(page_title="Trình Quét Tin Tức", layout="wide")

st.title("📰 Bảng Tin Tức Theo Từ Khóa")
st.markdown("Ứng dụng này tự động quét các trang tin tức dựa trên danh sách website và từ khóa bạn cung cấp.")

# Tải dữ liệu
data = load_data('news_data.csv')

if data is not None:
    st.sidebar.header("Tùy chọn")

    # Cho phép người dùng chọn các trang web để quét
    all_sites = data['Website'].unique()
    selected_sites = st.sidebar.multiselect("Chọn trang web để quét:", options=all_sites, default=all_sites)

    if st.sidebar.button("🚀 Bắt đầu quét tin tức"):
        if not selected_sites:
            st.warning("Vui lòng chọn ít nhất một trang web để quét.")
        else:
            st.info(f"Bắt đầu quá trình quét cho {len(selected_sites)} trang web đã chọn. Vui lòng chờ...")

            # Lọc dataframe dựa trên lựa chọn của người dùng
            sites_to_scan = data[data['Website'].isin(selected_sites)]

            total_found = 0

            # Lặp qua từng trang web trong danh sách đã chọn
            for index, row in sites_to_scan.iterrows():
                site_url = row['Website']
                keywords_str = row['Keywords']

                # Làm sạch và chuẩn bị danh sách từ khóa
                keywords = clean_keywords(keywords_str)

                if not keywords:
                    continue

                st.markdown("---")
                st.subheader(f"🔍 Kết quả từ: {site_url}")

                with st.spinner(f"Đang tìm kiếm trên {site_url}..."):
                    found_news = find_news_on_site(site_url, keywords)

                if found_news:
                    total_found += len(found_news)
                    for news_item in found_news:
                        st.markdown(f"**- [{news_item['title']}]({news_item['url']})**")
                        st.caption(f"Tìm thấy với từ khóa: `{news_item['keyword']}`")
                else:
                    st.write("Không tìm thấy bài viết nào phù hợp với từ khóa.")

            st.success(f"Hoàn thành! Tổng cộng tìm thấy {total_found} tin tức phù hợp.")

    st.markdown("---")
    st.header("Danh sách Website và Từ khóa")
    st.dataframe(data)